routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return redirect ('admin/categories');
})->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
    '/admin/categories' => 'CategoryController',
    '/admin/projects' => 'ProjectsController'
]);

resources/views/admin/category_create.blade.php
@extends('layouts.app')
@section('content')
        <h1>Category Create Page</h1>
        <form method="POST" action="{{route('categories.store')}}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input name="name" class="form-control" type="text">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
@endsection

resources/views/admin/category_edit.blade.php
@extends('layouts.app')
@section('content')
        <h1>Category Edit Page</h1>
    <form method="POST" action="{{route('categories.update',$category->id)}}">
            @csrf
            {{method_field('PUT')}}    
            <label for="name">Name</label>
        <input name="name" type="text" value="{{$category->category_name}}">
            <button type="submit">Update</button>
        </form>

resources/views/admin/category_index.blade.php
@extends('layouts.app')
@section('content')
        <h1>Your categories</h1>
  <ul class="list-group">
@foreach ($categories as $category)
  <li class="list-group-item" >
      <a href="categories/{{ $category->id }}">
          Name: {{$category->category_name}}
      </a>
      <div>
        <a href="{{route('categories.edit',$category->id)}}">
          <button class="btn btn-primary" type="submit">Edit</button>
      </a>
      <form style="display: inline" method="POST" action="{{route('categories.destroy',$category->id)}}">
        @csrf
        {{method_field('DELETE')}}        
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
      </div>
  </li>

@endforeach
  </ul>
  <a href="{{route('categories.create')}}"><button class="btn btn-primary" type="submit">Create new one</button></a>
  <a href="{{route('projects.index')}}"><button class="btn btn-primary" type="submit">Check Project list</button></a>
@endsection

resources/views/admin/category_show.blade.php
@extends('layouts.app')
@section('content')
        <h1>Projects</h1>
  <ul class="list-group">
@foreach ($category->projects as $project)
  <li class="list-group-item">
      <a href="{{route('projects.edit',$category->id)}}">
          Name: {{$project->name}}
      </a>
  </li>

@endforeach
  </ul>
<a href="{{route('projects.create')}}"><button type="submit">Create new one</button></a>
@endsection

resources/views/admin/home.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Admin page</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    admin page
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Docs</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://blog.laravel.com">Blog</a>
                    <a href="https://nova.laravel.com">Nova</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/admin/project_create.blade.php
@extends('layouts.app')
@section('content')
        <h1>Project Create Page</h1>
        <form method="POST" enctype="multipart/form-data" action="{{route('projects.store')}}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input name="name" class="form-control" type="text">
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                @foreach ($categories as $category)
            <input type="checkbox" name="categories[]" value="{{$category->id}}">
            <label for="">{{$category->category_name}}</label>
                @endforeach
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <select name="country" type="text">
                    <option value="">Please select</option>
                    @foreach ($countries as $country)
                    <option value="{{$country->id}}">{{$country->country_name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="creator">Creator</label>
                <select name="creator" type="text">
                    <option value="">Please select</option>
                    @foreach ($creators as $creator)
                    <option value="{{$creator->id}}">{{$creator->creator_name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="input-group control-group increment" >
                    <label for="creator">File</label>
                    <input type="file" name="image[]" class="form-control">
                    <div class="input-group-btn"> 
                      <button class="btn btn-success" type="button"><i class="glyphicon glyphicon-plus"></i>Add</button>
                    </div>
                  </div>
                  <div class="clone hide">
                    <div class="control-group input-group" style="margin-top:10px">
                      <input type="file" name="image[]" class="form-control">
                      <div class="input-group-btn"> 
                        <button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                      </div>
                    </div>
                  </div>
            <div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
<script type="text/javascript">

    $(document).ready(function() {

        $(".btn-success").click(function(){ 
            var html = $(".clone").html();
            $(".increment").after(html);
        });

        $("body").on("click",".btn-danger",function(){ 
            $(this).parents(".control-group").remove();
        });

    });

</script>
        @endsection

resources/views/admin/project_edit.blade.php
@extends('layouts.app')
@section('content')
        <h1>Project Create Page</h1>
<form method="POST" enctype="multipart/form-data" action="{{route('projects.update',$project->id)}}">
            @csrf
            {{method_field('PUT')}} 
            <div class="form-group">
                <label for="name">Name</label>
            <input name="name" type="text" class="form-control" value="{{$project->name}}">
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                @foreach ($categories as $category)
                <input type="checkbox" name="categories[]" value="{{$category->id}}"
                @if($project->categories->where('id',$category->id)->count())
                checked="checked"
                @endif
                >
                <label for="">{{$category->category_name}}</label>
                @endforeach
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <select name="country" type="text">
                    <option value="">Please select</option>
                    @foreach ($countries as $country)
                    <option value="{{$country->id}}"
                        @if($project->countries->where('id',$country->id)->count())
                        selected="selected"
                        @endif
                        >{{$country->country_name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="creator">Creator</label>
                <select name="creator" type="text">
                    <option value="">Please select</option>
                    @foreach ($creators as $creator)
                    <option value="{{$creator->id}}"
                        @if($project->creators->where('id',$creator->id)->count())
                        selected="selected"
                        @endif
                        >{{$creator->creator_name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="input-group control-group increment" >
                    <input type="file" name="image[]" class="form-control">
                    <div class="input-group-btn"> 
                      <button class="btn btn-success" type="button"><i class="glyphicon glyphicon-plus"></i>Add</button>
                    </div>
                  </div>
                  <div class="clone hide">
                    <div class="control-group input-group" style="margin-top:10px">
                      <input type="file" name="image[]" class="form-control">
                      <div class="input-group-btn"> 
                        <button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                      </div>
                    </div>
                  </div>
            <div>
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
<script type="text/javascript">

    $(document).ready(function() {

        $(".btn-success").click(function(){ 
            var html = $(".clone").html();
            $(".increment").after(html);
        });

        $("body").on("click",".btn-danger",function(){ 
            $(this).parents(".control-group").remove();
        });

    });

</script>
        @endsection

resources/views/admin/project_index.blade.php
@extends('layouts.app')
@section('content')
        <h1>Your projects</h1>
  <ul class="list-group">
@foreach ($projects as $project)
  <li class="list-group-item">
      <a href="projects/{{ $project->id }}">
          Name: {{$project->name}}
      </a>
      <div>
        <a href="{{route('projects.edit',$project->id)}}">
          <button class="btn btn-primary" type="submit">Edit</button>
      </a>
      <form style="display: inline" method="POST" action="{{route('projects.destroy',$project->id)}}">
        @csrf
        {{method_field('DELETE')}}        
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
      </div>
  </li>

@endforeach
  </ul>
  <a href="{{route('projects.create')}}"><button class="btn btn-primary" type="submit">Create new one</button></a>
  <a href="{{route('categories.index')}}"><button class="btn btn-primary" type="submit">Check Categories list</button></a>
@endsection

resources/views/admin/project_show.blade.php
@extends('layouts.app')
@section('content')
    <h1>Project Page</h1>
    <div>
        <label for="">Name</label>: <p>{{$project->name}}</p>
    </div>
@endsection